version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      babel:
        applies-to: version-updates
        patterns:
          - "@babel/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint*"
      prettier:
        applies-to: version-updates
        patterns:
          - "prettier*"
      stylelint:
        applies-to: version-updates
        patterns:
          - "stylelint*"
    open-pull-requests-limit: 99
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - kpfefferle
