name: Ember CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Node Modules Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Run Tests
        run: yarn test:ember

  ember-try:
    name: ember-try (${{ matrix.scenario }})
    needs: test
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          # - ember-release
          # - ember-beta
          - ember-classic
          # - embroider-safe
          # - embroider-optimized
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Node Modules Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn ember try:one ${{ matrix.scenario }} --skip-cleanup=true

  # deploy:
  #   if: contains(github.ref, 'master')
  #   name: Deploy
  #   needs: ember-try
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x
  #     - name: Install Dependencies
  #       run: yarn install
  #     - name: Deploy
  #       run: yarn ember deploy production --verbose
